---
development: &default
  mongo_uri: mongodb://localhost:27017/cg_dev
  cloudinary:
    cloud_name: hxgvncv7u
    api_key: 844974134959653
    api_secret: 2scRx2fF3Vuw1qS6tu0FGli69Po
    cdn_subdomain: true
test:
  <<: *default
  mongo_uri: mongodb://localhost:27017/cg_test
production:
  <<: *default
  mongo_uri: mongodb://heroku_1qqrwjjv:6j1mh19jfgfn4up520imdbh3g8@ds055535.mongolab.com:55535/heroku_1qqrwjjv
