development:
  expiration: 30
  dbname: cg_dev
test:
  expiration: 30
  dbname: cg_test
production:
  expiration: 15
  dbname: heroku_1qqrwjjv
  dbhost: ds055535.mongolab.com
  dbport: 61298
  dbuser: heroku_1qqrwjjv
  dbpass: 6j1mh19jfgfn4up520imdbh3g8
